### ISSUE TITLE
Landing page for Council of Paris 2019

### ISSUE THREAD

**Issue by bmann** [ethereum-magicians/scrolls#46]
The last two were hosted on the Ethereum Events Global that @bmann maintains --> eg https://ethereumevents.global/events/2018-council-of-prague/

It's unclear if these web pages have added valuable. They are a prettier place to link to for sponsors and have design flexibility, but also meant another page for registration.

Suggest picking a ticketing platform first, and just using that as the "home page" -- Maybe we just want to use Kickback https://kickback.events/? Would definitely solve the attendance issue.

**Comment by markoprljic** [comment]
My suggestion would be to have the event on multiple places "featured". A dedicated website is mandatory IMHO, aside from ticketing service landing page and Ethereum events site.
We can create a simple one-page landing page (marketing site) to promote this and future events and CTA's can link to a single ticketing service of choice.
@tomislavmamic will probably prepare content and CTA and I can take it from there.

**Comment by tomislavmamic** [comment]
Hi, I agree with @markoprljic . I'll draft the text and CTAs for website, and add links to existing media from previous events.

**Comment by bmann** [comment]
The "dedicated web page" doesn't seem to have gotten much traffic in the past.

I have created one in the same way I did the last two - see https://ethereumevents.global/events/2019-council-of-paris/

Please file issues in the repo there for edits OR pull requests. But don't feel you NEED to use that -- feel free to create a website using a different service.

I am going to call this the landing page issue and create a separate ticketing one.

**Comment by ethernian** [comment]
@boris, 
as agreed with @tomislavmamic I have created a text for sponsors to be used on the landing page. Feel free to use it, but please make a proofread and replace XX/YY with real numbers.

==============
Ethereum Magicians Council is a regular gathering of Ethereum Community focused on current progress and challenges in Ethereum community and technology. In contrast to usual conferences and meetups where preselected speakers presenting their work to broader audience, Magicians Councils are organized around working groups called Rings open for anyone to participate. The goal of the Council is to facilitate communication in the community across usual circles. It gives anyone a chance to be heard, to understand concerns of others, to find colleagues to work together on some topic or start a new one.

Because of great inclusivity of the Council and its unique format, the number of participants have arose quickly. Starting from XX people in Berlin in June 2018, we counted almost YY people in Prague in Nov 2018. Although volunteers become no money, it becomes challenging to organize the event for such amount of people and cover all the costs. That is why we need your help. 

We appreciate our sponsors very much and would like to offer various perks as a part of our sponsorship packages. In particular we are offering logo and poster placements in our video recording and in venue which becomes visible not only for hunderts of participants during the event, but also online for broader public for a long time hereafter.

Please see our sponsorship packages here. We would be pleased to welcome you as our sponsor.

**Comment by bmann** [comment]
@ethernian I moved this to #57 so we have a separate item for tracking. This thread is for the landing page.

Talked to @tomislavmamic in chat about this. The EthereumEvents site can be used, I can't volunteer to maintain it. Will need someone familiar with Jekyll (basic markdown and Git skills) to make edits. I can easily add a collaborator.

Until we have a volunteer to make edits / maintain the site, suggest we don't promote that URL.

**Comment by bmann** [comment]
@tomislavmamic looks like you do want to use the EEG Jekyll site, so I'm going to consider this closed. Am posting about a volunteer to help with this.
